


    //  $(window).scroll(function () {
    //    $('aside').hide();
    //     if($(this).scrollTop()==0){
    //      $('aside').show();
        
    //     }
    // });



// var countries = {
//   "United Kingdom": {
//     "France": 5,
//   },
//   "France": {
//     "United Kindgom": 7
//   }
// }

// var list = Object.keys(countries);

// countries[country1][country2] = countries[country2][country1]


// define country object/ARRAY
// define flag object/ARRAY
// define number in object/array of average country-for-country vote


// SELECT an element from the drop down
// Get the matching element from an OBJECT or ARRAY
// if the user SELECTs X country then display X flag
// if the user SELECTs y country then display Y flag
// if the XY country averages are === or if the difference is <2 display a reltionshi status of IN LOVE
// if the difference between the XY avages is >2 but <5 then display a relationship status of luke/warm seeing other people
// if the difference between the XY average is >5 but <9 then display a relationship status of COLD AND DISTANT
// if the difference between the XY average is > 9 than display a relationship of BAD and UGLY



//creative variables countries/flags/hearts
	// var countries = [france][germany][sweden];
	// var flags = [france.svg][germany.svg][sweden.svg];
	// var hearts = [hearts.svg][broken.svg];
	// var list = Object.keys(countries);

//define event handlers for countries/flags/hearts

// SELECT an element from the drop down

// Get the matching element from an OBJECT or ARRAY

// if the user SELECTs X country then display X flag

// if the user SELECTs y country then display Y flag



// var countries = {
//   "sweden": {
//     "france": 5,
//   },
//   "france": {
//     "sweden": 7,
//   },
//   "germany": {
//   	"france": 10,
//   },
//   "france": {
//   	"germany": 2,
//   },
//   //  "sweden": {
//   //   "sweden": 25,
//   // },
//   // "france": {
//   //   "france": 25,
//   // },
// }

var countries = {

"albania":  {
    "albania":-1,
    "slovakia":-1 ,
    "armenia":0.3 ,
    "austria":1.7 ,
    "azerbaijan":3.3 ,
    "belarus":0.5 ,
    "belgium":0 ,
    "bosnia & Herzegovina":5.3 ,
    "bulgaria":0 ,
    "croatia":0.4 ,
    "cyprus":3.3 ,
    "denmark":0.3 ,
    "estonia":0 ,
    "f.Y.R. Macedonia":6 ,
    "finland":0 ,
    "france":0.9 ,
    "georgia":0 ,
    "germany":3.2 ,
    "greece":9.9 ,
    "hungary":2.7 ,
    "iceland":0.8 ,
    "ireland":0.7 ,
    "israel":2.2 ,
    "italy":10.3 ,
    "latvia":0 ,
    "lithuania":0 ,
    "malta":1.3 ,
    "moldova":0 ,
    "montenegro":6 ,
    "norway":1.8 ,
    "poland":0 ,
    "portugal":0 ,
    "romania":1.5 ,
    "russia":1.5 ,
    "san marino":3 ,
    "serbia":3.4 ,
    "slovenia":0 ,
    "spain":4.5 ,
    "sweden":3 ,
    "switzerland":0 ,
    "the Netherlands":1.3 ,
    "turkey":8.9 ,
    "u.K.":1.4 ,
    "ukraine":1.
},

"andorra": {
    "italy":-1,
    "montenegro":-1,
    "san marino":-1,
    "slovakia":-1,
    "albania":0,
    "armenia":0,
    "austria":0,
    "azerbaijan":3.5,
    "belarus":0,
    "belgium":1,
    "bosnia & Herzegovina":0,
    "bulgaria":0,
    "croatia":0,
    "cyprus":2,
    "denmark":2,
    "estonia":0,
    "f.Y.R. Macedonia":0,
    "finland":5.3,
    "france":4.3,
    "georgia":0,
    "germany":0.8,
    "greece":3.5,
    "hungary":6,
    "iceland":2.7,
    "ireland":1.3,
    "israel":3.8,
    "latvia":3,
    "lithuania":2.7,
    "malta":1.8,
    "moldova":1,
    "norway":2.6,
    "poland":0,
    "portugal":8,
    "romania":3.3,
    "russia":2.3,
    "serbia":0.5,
    "slovenia":0,
    "spain":10,
    "sweden":2.8,
    "switzerland":0.5,
    "the Netherlands":0,
    "turkey":0.5,
    "u.K.":1,
    "ukraine":5.5
},

"armenia": {
    "armenia":-1,
    "slovakia":-1,
    "albania":0,
    "austria":1.5,
    "azerbaijan":0.2,
    "belarus":5.8,
    "belgium":0,
    "bosnia & Herzegovina":1,
    "bulgaria":4,
    "croatia":0.7,
    "cyprus":0,
    "denmark":1.4,
    "estonia":0,
    "f.Y.R. Macedonia":3.5,
    "finland":0,
    "france":3.4,
    "georgia":9.4,
    "germany":0.8,
    "greece":7.4,
    "hungary":0,
    "iceland":0.8,
    "ireland":0.6,
    "israel":1.5,
    "italy":2.3,
    "latvia":0,
    "lithuania":0,
    "malta":1.5,
    "moldova":0.8,
    "montenegro":12,
    "norway":3.5,
    "poland":0,
    "portugal":1.3,
    "romania":0.6,
    "russia":10.4,
    "san marino":3,
    "serbia":2.8,
    "slovenia":0,
    "spain":1.3,
    "sweden":1.4,
    "switzerland":1.7,
    "the Netherlands":2,
    "turkey":0.8,
    "u.K.":1.1,
    "ukraine":7
},

"austria": {
    "austria":-1,
    "albania":5.3,
    "armenia":5.7,
    "azerbaijan":5,
    "belarus":0,
    "belgium":1,
    "bosnia & Herzegovina":6.7,
    "bulgaria":6,
    "croatia":4,
    "cyprus":0.8,
    "denmark":2.7,
    "estonia":2.2,
    "f.Y.R. Macedonia":0.2,
    "finland":0.6,
    "france":0.9,
    "georgia":0,
    "germany":4.9,
    "greece":1.5,
    "hungary":1.4,
    "iceland":1.5,
    "ireland":2.3,
    "israel":1.3,
    "italy":3.4,
    "latvia":3.6,
    "lithuania":0,
    "malta":2,
    "moldova":2,
    "montenegro":0,
    "norway":1,
    "poland":3.1,
    "portugal":0.2,
    "romania":2.8,
    "russia":2.1,
    "san marino":0,
    "serbia":10.6,
    "slovakia":0,
    "slovenia":0.9,
    "spain":0.4,
    "sweden":3.6,
    "switzerland":1.3,
    "the Netherlands":4.3,
    "turkey":4.7,
    "u.K.":2.8,
    "ukraine":1.8
},

"azerbaijan": {
    "azerbaijan":-1,
    "bulgaria":-1 ,
    "slovakia":-1 ,
    "albania":0.3 ,
    "armenia":0 ,
    "austria":0.5 ,
    "belarus":4.7 ,
    "belgium":0 ,
    "bosnia & Herzegovina":1 ,
    "croatia":2.5 ,
    "cyprus":1 ,
    "denmark":1.3 ,
    "estonia":1 ,
    "f.Y.R. Macedonia":0 ,
    "finland":0 ,
    "france":0 ,
    "georgia":8 ,
    "germany":0.1 ,
    "greece":3.9 ,
    "hungary":2.5 ,
    "iceland":0 ,
    "ireland":0.3 ,
    "israel":4 ,
    "italy":0.3 ,
    "latvia":0 ,
    "lithuania":2 ,
    "malta":5.3 ,
    "moldova":4.2 ,
    "montenegro":0 ,
    "norway":2.5 ,
    "poland":1 ,
    "portugal":0 ,
    "romania":4.9 ,
    "russia":6.1 ,
    "san marino":3 ,
    "serbia":0.5 ,
    "slovenia":0 ,
    "spain":0 ,
    "sweden":1.7 ,
    "switzerland":0 ,
    "the Netherlands":0 ,
    "turkey":12 ,
    "u.K.":1 ,
    "ukraine":9.6
 },

"belarus": {
    "belarus":-1 ,
    "slovakia":-1 ,
    "albania":0 ,
    "armenia":5.4 ,
    "austria":0 ,
    "azerbaijan":7.1 ,
    "belgium":0 ,
    "bosnia & Herzegovina":0.4 ,
    "bulgaria":0 ,
    "croatia":1 ,
    "cyprus":2 ,
    "denmark":0.2 ,
    "estonia":2 ,
    "f.Y.R. Macedonia":0.4 ,
    "finland":1.1 ,
    "france":0.6 ,
    "georgia":6.2 ,
    "germany":0.7 ,
    "greece":2.7 ,
    "hungary":1.2 ,
    "iceland":0.5 ,
    "ireland":0.1 ,
    "israel":4 ,
    "italy":0.8 ,
    "latvia":1.5 ,
    "lithuania":3.5 ,
    "malta":2.1 ,
    "moldova":4.4 ,
    "montenegro":0 ,
    "norway":3.2 ,
    "poland":2.3 ,
    "portugal":0 ,
    "romania":0.5 ,
    "russia":10.6 ,
    "san marino":0 ,
    "serbia":2.6 ,
    "slovenia":1.3 ,
    "spain":0.2 ,
    "sweden":1.9 ,
    "switzerland":2.5 ,
    "the Netherlands":0.7 ,
    "turkey":1.1 ,
    "u.K.":0.5 ,
    "ukraine":8.7
},

"belgium": {
    "belgium":-1 ,
    "albania":2.3 ,
    "armenia":6.9 ,
    "austria":3.9 ,
    "azerbaijan":3.3 ,
    "belarus":0 ,
    "bosnia & Herzegovina":0.5 ,
    "bulgaria":4 ,
    "croatia":1.2 ,
    "cyprus":1.5 ,
    "denmark":2.7 ,
    "estonia":1.2 ,
    "f.Y.R. Macedonia":0 ,
    "finland":1 ,
    "france":2.6 ,
    "georgia":2 ,
    "germany":2.4 ,
    "greece":4.8 ,
    "hungary":1.8 ,
    "iceland":1.5 ,
    "ireland":1.5 ,
    "israel":3.5 ,
    "italy":3 ,
    "latvia":3.6 ,
    "lithuania":0.5 ,
    "malta":1.7 ,
    "moldova":1.1 ,
    "montenegro":0 ,
    "norway":3 ,
    "poland":0.6 ,
    "portugal":2.4 ,
    "romania":1.8 ,
    "russia":2.1 ,
    "san marino":0 ,
    "serbia":2.1 ,
    "slovakia":0 ,
    "slovenia":0.4 ,
    "spain":3.3 ,
    "sweden":3.6 ,
    "switzerland":0.3 ,
    "the Netherlands":8.4 ,
    "turkey":6.5 ,
    "u.K.":1.8 ,
    "ukraine":1.6
},

"bosnia & Herzegovina": {
    "bosnia & Herzegovina":-1,
    "montenegro":-1,
    "san marino":-1,
    "albania":3.5,
    "armenia":1.2,
    "austria":2.3,
    "azerbaijan":5,
    "belarus":2,
    "belgium":1.4,
    "bulgaria":6,
    "croatia":8.4,
    "cyprus":0,
    "denmark":0.3,
    "estonia":2,
    "f.Y.R. Macedonia":7.2,
    "finland":1.4,
    "france":2.9,
    "georgia":1.3,
    "germany":1.7,
    "greece":2.8,
    "hungary":0.2,
    "iceland":0.1,
    "ireland":2.3,
    "israel":2.9,
    "italy":4,
    "latvia":0.7,
    "lithuania":0.3,
    "malta":2.5,
    "moldova":0.6,
    "norway":1.5,
    "poland":2.1,
    "portugal":0.2,
    "romania":1.2,
    "russia":1.3,
    "serbia":11.1,
    "slovakia":0,
    "slovenia":6.7,
    "spain":1.5,
    "sweden":3.5,
    "switzerland":0.7,
    "the Netherlands":1.3,
    "turkey":6.2,
    "u.K.":1.6,
    "ukraine":1.9
},

"bulgaria": {
    "bulgaria":-1,
    "montenegro":-1,
    "san marino":-1,
    "slovakia":-1,
    "albania":0.8,
    "armenia":7.7,
    "austria":5,
    "azerbaijan":7.5,
    "belarus":0.7,
    "belgium":0,
    "bosnia & Herzegovina":1.6,
    "croatia":0.5,
    "cyprus":4.7,
    "denmark":1.1,
    "estonia":0,
    "f.Y.R. Macedonia":6.3,
    "finland":1.3,
    "france":0,
    "georgia":1.4,
    "germany":1.7,
    "greece":9,
    "hungary":2.2,
    "iceland":0.8,
    "ireland":0.5,
    "israel":0.4,
    "italy":0,
    "latvia":0,
    "lithuania":1.2,
    "malta":0,
    "moldova":1.6,
    "norway":0.7,
    "poland":0,
    "portugal":0,
    "romania":2,
    "russia":4,
    "serbia":4.3,
    "slovenia":0,
    "spain":0.6,
    "sweden":1.5,
    "switzerland":0,
    "the Netherlands":0,
    "turkey":6.6,
    "u.K.":2.1,
    "ukraine":4.2
},

"croatia": {
    "croatia":-1 ,
    "montenegro":-1 ,
    "san marino":-1 ,
    "albania":5.2 ,
    "armenia":0 ,
    "austria":0.9 ,
    "azerbaijan":4.5 ,
    "belarus":0 ,
    "belgium":0.6 ,
    "bosnia & Herzegovina":8.2 ,
    "bulgaria":6 ,
    "cyprus":3.2 ,
    "denmark":1.7 ,
    "estonia":1.6 ,
    "f.Y.R. Macedonia":7.1 ,
    "finland":1 ,
    "france":0.9 ,
    "georgia":1.8 ,
    "germany":1.2 ,
    "greece":2.9 ,
    "hungary":2 ,
    "iceland":0.6 ,
    "ireland":2.1 ,
    "israel":1.2 ,
    "italy":5 ,
    "latvia":1.8 ,
    "lithuania":1.1 ,
    "malta":4.7 ,
    "moldova":0.6 ,
    "norway":1.5 ,
    "poland":0 ,
    "portugal":1.3 ,
    "romania":0.9 ,
    "russia":3.6 ,
    "serbia":10.6 ,
    "slovakia":4 ,
    "slovenia":6.4 ,
    "spain":1.5 ,
    "sweden":1.2 ,
    "switzerland":0.4 ,
    "the Netherlands":1.6 ,
    "turkey":2.8 ,
    "u.K.":2.5 ,
    "ukraine":3.7
},

"cyprus": {
    "cyprus":-1,
    "montenegro":-1,
    "san marino":-1,
    "albania":0.7,
    "armenia":6,
    "austria":0.7,
    "azerbaijan":7,
    "belarus":2,
    "belgium":1,
    "bosnia & Herzegovina":0.1,
    "bulgaria":10,
    "croatia":2.5,
    "denmark":2.2,
    "estonia":1.5,
    "f.Y.R. Macedonia":0.6,
    "finland":0.7,
    "france":0.9,
    "georgia":2.6,
    "germany":0.2,
    "greece":11.9,
    "hungary":0.9,
    "iceland":1.8,
    "ireland":2.1,
    "israel":2.9,
    "italy":3.8,
    "latvia":0.9,
    "lithuania":1.1,
    "malta":3.3,
    "moldova":0.5,
    "norway":2.5,
    "poland":0.8,
    "portugal":1.6,
    "romania":3.7,
    "russia":4.7,
    "serbia":5.1,
    "slovakia":0,
    "slovenia":1.2,
    "spain":3.7,
    "sweden":2.2,
    "switzerland":0.9,
    "the Netherlands":1.3,
    "turkey":0.8,
    "u.K.":2.2,
    "ukraine":4.1
},

"czech Republic": {
    "czech Republic":-1,
    "austria":-1 ,
    "belgium":-1 ,
    "cyprus":-1 ,
    "italy":-1 ,
    "montenegro":-1 ,
    "san marino":-1 ,
    "slovakia":-1 ,
    "switzerland":-1 ,
    "the Netherlands":-1 ,
    "albania":0 ,
    "armenia":11.3 ,
    "azerbaijan":10 ,
    "belarus":2 ,
    "bosnia & Herzegovina":1.7 ,
    "bulgaria":7 ,
    "croatia":0 ,
    "denmark":1 ,
    "estonia":0 ,
    "f.Y.R. Macedonia":5 ,
    "finland":0 ,
    "france":0 ,
    "georgia":2.5 ,
    "germany":0 ,
    "greece":2.7 ,
    "hungary":0 ,
    "iceland":1 ,
    "ireland":0 ,
    "israel":2 ,
    "latvia":1.5 ,
    "lithuania":0 ,
    "malta":0 ,
    "moldova":0 ,
    "norway":1.5 ,
    "poland":0 ,
    "portugal":3.5 ,
    "romania":0 ,
    "russia":7 ,
    "serbia":7 ,
    "slovenia":0 ,
    "spain":0 ,
    "sweden":0 ,
    "turkey":0.3 ,
    "u.K.":2 ,
    "ukraine":8.3
},


"denmark": {
    "denmark":-1,
    "slovakia":-1,
    "albania":1.5,
    "armenia":0.3,
    "austria":2.8,
    "azerbaijan":1.4,
    "belarus":0,
    "belgium":2.7,
    "bosnia & Herzegovina":3.5,
    "bulgaria":0,
    "croatia":0,
    "cyprus":2.1,
    "estonia":4.3,
    "f.Y.R. Macedonia":0,
    "finland":3.3,
    "france":1.9,
    "georgia":0,
    "germany":3.3,
    "greece":1.3,
    "hungary":1.4,
    "iceland":6.1,
    "ireland":3.1,
    "israel":0.8,
    "italy":1.4,
    "latvia":3.9,
    "lithuania":0.9,
    "malta":3.8,
    "moldova":0.9,
    "montenegro":0,
    "norway":5.2,
    "poland":0.9,
    "portugal":0.6,
    "romania":1.7,
    "russia":1.6,
    "san marino":0,
    "serbia":1.9,
    "slovenia":0.9,
    "spain":0.2,
    "sweden":9.6,
    "switzerland":0.1,
    "the Netherlands":3.9,
    "turkey":3.6,
    "u.K.":2.5,
    "ukraine":1.7
},

"estonia": {
    "estonia":-1,
    "albania":0.2,
    "armenia":0.7,
    "austria":2.8,
    "azerbaijan":2.1,
    "belarus":1.8,
    "belgium":2.8,
    "bosnia & Herzegovina":0,
    "bulgaria":1,
    "croatia":1.1,
    "cyprus":1.1,
    "denmark":4.3,
    "f.Y.R. Macedonia":0,
    "finland":6.1,
    "france":1.9,
    "georgia":4.2,
    "germany":2.2,
    "greece":0.7,
    "hungary":2.9,
    "iceland":3.6,
    "ireland":2.4,
    "israel":1.5,
    "italy":2.6,
    "latvia":8.4,
    "lithuania":1.9,
    "malta":2.1,
    "moldova":0.8,
    "montenegro":0,
    "norway":3.9,
    "poland":0.8,
    "portugal":0.3,
    "romania":0.3,
    "russia":8.6,
    "san marino":0,
    "serbia":0.1,
    "slovakia":0,
    "slovenia":1.1,
    "spain":0.7,
    "sweden":6.7,
    "switzerland":1.3,
    "the Netherlands":2.6,
    "turkey":0.8,
    "u.K.":2.1,
    "ukraine":4.3
},

"f.Y.R. Macedonia": {
    "f.Y.R. Macedonia":-1,
    "albania":11.2,
    "armenia":2,
    "austria":1.3,
    "azerbaijan":2.3,
    "belarus":3,
    "belgium":1.6,
    "bosnia & Herzegovina":7,
    "bulgaria":8,
    "croatia":7.3,
    "cyprus":0.7,
    "denmark":1.4,
    "estonia":0,
    "finland":0.8,
    "france":0.3,
    "georgia":1,
    "germany":0.6,
    "greece":2.8,
    "hungary":1.6,
    "iceland":0.2,
    "ireland":0.8,
    "israel":1.3,
    "italy":4.5,
    "latvia":0.6,
    "lithuania":0.5,
    "malta":1.7,
    "moldova":1.6,
    "montenegro":12,
    "norway":1.5,
    "poland":1.3,
    "portugal":1,
    "romania":1.9,
    "russia":3.5,
    "san marino":0,
    "serbia":9.6,
    "slovakia":0,
    "slovenia":4.3,
    "spain":0.4,
    "sweden":2.3,
    "switzerland":0,
    "the Netherlands":2.4,
    "turkey":7.1,
    "u.K.":1.6,
    "ukraine":2.6
},

"finland": {
    "finland":-1,
    "albania":1.5,
    "armenia":0.7,
    "austria":2.7,
    "azerbaijan":1,
    "belarus":0,
    "belgium":1.3,
    "bosnia & Herzegovina":2.1,
    "bulgaria":5,
    "croatia":1.2,
    "cyprus":2.1,
    "denmark":3.2,
    "estonia":9.6,
    "f.Y.R. Macedonia":0.1,
    "france":2.2,
    "georgia":1.4,
    "germany":1.2,
    "greece":1.3,
    "hungary":5.3,
    "iceland":4.4,
    "ireland":3,
    "israel":4.8,
    "italy":0.8,
    "latvia":3.7,
    "lithuania":1.1,
    "malta":1.9,
    "moldova":0.3,
    "montenegro":0,
    "norway":5.4,
    "poland":0,
    "portugal":0.6,
    "romania":0.4,
    "russia":4.2,
    "san marino":0,
    "serbia":3.7,
    "slovakia":0,
    "slovenia":0.7,
    "spain":0.5,
    "sweden":7.5,
    "switzerland":1.8,
    "the Netherlands":3.8,
    "turkey":2.5,
    "u.K.":1.1,
    "ukraine":1.9
},

"france": {
    "france":-1,
    "albania":0.3,
    "armenia":9,
    "austria":3.4,
    "azerbaijan":2.1,
    "belarus":0,
    "belgium":3.5,
    "bosnia & Herzegovina":1.6,
    "bulgaria":5,
    "croatia":1.6,
    "cyprus":0.9,
    "denmark":2.5,
    "estonia":2.6,
    "f.Y.R. Macedonia":0,
    "finland":1,
    "georgia":0,
    "germany":2.5,
    "greece":2.1,
    "hungary":1.2,
    "iceland":0.7,
    "ireland":1.5,
    "israel":7.3,
    "italy":4,
    "latvia":1.4,
    "lithuania":0.3,
    "malta":1.8,
    "moldova":1.3,
    "montenegro":0,
    "norway":1.8,
    "poland":1.5,
    "portugal":7.2,
    "romania":2.3,
    "russia":1.6,
    "san marino":0,
    "serbia":7,
    "slovakia":0,
    "slovenia":1.3,
    "spain":3.9,
    "sweden":2.5,
    "switzerland":0.3,
    "the Netherlands":2.5,
    "turkey":8.1,
    "u.K.":2.1,
    "ukraine":0.7
},

"georgia": {
    "georgia":-1,
    "slovakia":-1,
    "albania":1,
    "armenia":11.2,
    "austria":6.5,
    "azerbaijan":8.7,
    "belarus":6.3,
    "belgium":0,
    "bosnia & Herzegovina":0,
    "bulgaria":0,
    "croatia":1,
    "cyprus":0,
    "denmark":1.2,
    "estonia":0,
    "f.Y.R. Macedonia":0.5,
    "finland":0,
    "france":0.3,
    "germany":1,
    "greece":2.7,
    "hungary":1,
    "iceland":0,
    "ireland":0,
    "israel":3.5,
    "italy":3.3,
    "latvia":1,
    "lithuania":6.3,
    "malta":1,
    "moldova":1.8,
    "montenegro":0,
    "norway":3,
    "poland":0,
    "portugal":0,
    "romania":0,
    "russia":5.4,
    "san marino":0,
    "serbia":1.2,
    "slovenia":0,
    "spain":0.3,
    "sweden":1.8,
    "switzerland":0.5,
    "the Netherlands":0,
    "turkey":5,
    "u.K.":0.9,
    "ukraine":8.1
},

"germany": {
    "germany":-1,
    "albania":2,
    "armenia":3.4,
    "austria":3.1,
    "azerbaijan":0.7,
    "belarus":0,
    "belgium":2.4,
    "bosnia & Herzegovina":2.3,
    "bulgaria":4,
    "croatia":3.1,
    "cyprus":1.5,
    "denmark":4.4,
    "estonia":3.4,
    "f.Y.R. Macedonia":0,
    "finland":1.8,
    "france":1.4,
    "georgia":0,
    "greece":5.5,
    "hungary":2.1,
    "iceland":2,
    "ireland":1.8,
    "israel":3.1,
    "italy":1.8,
    "latvia":3.3,
    "lithuania":0.1,
    "malta":2.8,
    "moldova":0.6,
    "montenegro":0,
    "norway":2.4,
    "poland":5.1,
    "portugal":1.1,
    "romania":0.7,
    "russia":2.9,
    "san marino":0,
    "serbia":6.3,
    "slovakia":0,
    "slovenia":1,
    "spain":0.9,
    "sweden":2.4,
    "switzerland":1.1,
    "the Netherlands":2.1,
    "turkey":9.2,
    "u.K.":1.5,
    "ukraine":0.9
},

"greece": {
    "greece":-1,
    "albania":9.5,
    "armenia":6,
    "austria":3.5,
    "azerbaijan":4.9,
    "belarus":1.5,
    "belgium":2.3,
    "bosnia & Herzegovina":0.6,
    "bulgaria":12,
    "croatia":2.2,
    "cyprus":11.6,
    "denmark":1.2,
    "estonia":1.7,
    "f.Y.R. Macedonia":0,
    "finland":1.2,
    "france":2.2,
    "georgia":5,
    "germany":0.6,
    "hungary":1.1,
    "iceland":0.8,
    "ireland":1.1,
    "israel":1.6,
    "italy":4.8,
    "latvia":1.6,
    "lithuania":0.5,
    "malta":3.1,
    "moldova":2.5,
    "montenegro":0,
    "norway":2.5,
    "poland":2.4,
    "portugal":0.8,
    "romania":3.4,
    "russia":3.6,
    "san marino":0,
    "serbia":4.4,
    "slovakia":2,
    "slovenia":1.5,
    "spain":2.7,
    "sweden":0.9,
    "switzerland":0.9,
    "the Netherlands":2,
    "turkey":2.4,
    "u.K.":2.1,
    "ukraine":3.8
},

"hungary": {
    "hungary":-1,
    "albania":2.5,
    "armenia":2,
    "austria":5.3,
    "azerbaijan":6.8,
    "belarus":1.3,
    "belgium":2.3,
    "bosnia & Herzegovina":0,
    "bulgaria":10,
    "croatia":1.2,
    "cyprus":2.6,
    "denmark":2.7,
    "estonia":2.3,
    "f.Y.R. Macedonia":0,
    "finland":0.9,
    "france":1.1,
    "georgia":1.8,
    "germany":1,
    "greece":3.6,
    "iceland":4.5,
    "ireland":2,
    "israel":3.2,
    "italy":2.4,
    "latvia":0.3,
    "lithuania":0,
    "malta":2.5,
    "moldova":1.8,
    "montenegro":0,
    "norway":3.2,
    "poland":2.6,
    "portugal":0,
    "romania":2.1,
    "russia":2.6,
    "san marino":4,
    "serbia":5,
    "slovakia":0,
    "slovenia":2.3,
    "spain":1.2,
    "sweden":3.5,
    "switzerland":0.8,
    "the Netherlands":7.3,
    "turkey":2.5,
    "u.K.":2.7,
    "ukraine":3.3
},

"iceland": {
    "iceland":-1,
    "albania":1.8,
    "armenia":1.1,
    "austria":3.1,
    "azerbaijan":2.7,
    "belarus":1,
    "belgium":1.9,
    "bosnia & Herzegovina":0.5,
    "bulgaria":0,
    "croatia":1.6,
    "cyprus":2.9,
    "denmark":9.1,
    "estonia":4.9,
    "f.Y.R. Macedonia":0,
    "finland":6.1,
    "france":3,
    "georgia":0.4,
    "germany":1.7,
    "greece":1.7,
    "hungary":3.8,
    "ireland":1.1,
    "israel":0.1,
    "italy":0.8,
    "latvia":3.6,
    "lithuania":1.2,
    "malta":1.5,
    "moldova":1,
    "montenegro":0,
    "norway":6,
    "poland":1.3,
    "portugal":2.7,
    "romania":1.9,
    "russia":1.9,
    "san marino":0,
    "serbia":2.7,
    "slovakia":0,
    "slovenia":1.1,
    "spain":1.2,
    "sweden":5.8,
    "switzerland":1.3,
    "the Netherlands":3.2,
    "turkey":1.1,
    "u.K.":1.3,
    "ukraine":2.7
},

"ireland": {
    "ireland":-1,
    "albania":0.3,
    "armenia":0,
    "austria":2.4,
    "azerbaijan":0.9,
    "belarus":0,
    "belgium":4.6,
    "bosnia & Herzegovina":0.3,
    "bulgaria":0,
    "croatia":1.8,
    "cyprus":1.3,
    "denmark":6.1,
    "estonia":5.9,
    "f.Y.R. Macedonia":0,
    "finland":1.3,
    "france":1.7,
    "georgia":1.2,
    "germany":2.7,
    "greece":1,
    "hungary":1.1,
    "iceland":2.6,
    "israel":1.1,
    "italy":1.6,
    "latvia":6.6,
    "lithuania":6.3,
    "malta":3.5,
    "moldova":1.6,
    "montenegro":0,
    "norway":4,
    "poland":1,
    "portugal":0.2,
    "romania":2.4,
    "russia":2.6,
    "san marino":0,
    "serbia":1,
    "slovakia":0,
    "slovenia":2.4,
    "spain":0.9,
    "sweden":5.2,
    "switzerland":1.5,
    "the Netherlands":3.8,
    "turkey":0.3,
    "u.K.":5.4,
    "ukraine":2.8
},

"israel": {
    "israel":-1,
    "albania":0,
    "armenia":6.7,
    "austria":2,
    "azerbaijan":5.7,
    "belarus":4,
    "belgium":2.3,
    "bosnia & Herzegovina":0.2,
    "bulgaria":0,
    "croatia":1.9,
    "cyprus":1.6,
    "denmark":3.5,
    "estonia":2,
    "f.Y.R. Macedonia":0,
    "finland":1.2,
    "france":1.3,
    "georgia":3,
    "germany":1,
    "greece":3.1,
    "hungary":1.9,
    "iceland":2.2,
    "ireland":0.6,
    "italy":1,
    "latvia":1.4,
    "lithuania":1.3,
    "malta":1.8,
    "moldova":1.9,
    "montenegro":0,
    "norway":3.3,
    "poland":0,
    "portugal":0.3,
    "romania":5.4,
    "russia":6.9,
    "san marino":0,
    "serbia":1.4,
    "slovakia":0,
    "slovenia":0.9,
    "spain":3.8,
    "sweden":4.1,
    "switzerland":1,
    "the Netherlands":3.6,
    "turkey":1.1,
    "u.K.":1.6,
    "ukraine":5.7
},

"italy": {
    "bulgaria":-1,
    "israel":-1,
    "italy":-1,
    "latvia":-1,
    "slovakia":-1,
    "albania":12,
    "armenia":0,
    "austria":4,
    "azerbaijan":0,
    "belarus":0,
    "belgium":0,
    "bosnia & Herzegovina":1.3,
    "croatia":0,
    "cyprus":4.5,
    "denmark":2.8,
    "estonia":3,
    "f.Y.R. Macedonia":1,
    "finland":2,
    "france":0.2,
    "georgia":0,
    "germany":3.8,
    "greece":2.4,
    "hungary":0.6,
    "iceland":2.4,
    "ireland":2.5,
    "lithuania":2,
    "malta":4.3,
    "moldova":5.3,
    "montenegro":0,
    "norway":2,
    "poland":4.5,
    "portugal":0,
    "romania":6.3,
    "russia":2,
    "san marino":0,
    "serbia":4.5,
    "slovenia":0,
    "spain":1,
    "sweden":0,
    "switzerland":1.3,
    "the Netherlands":1.3,
    "turkey":3.5,
    "u.K.":3.6,
    "ukraine":6.3
},

"latvia": {
    "latvia":-1,
    "slovakia":-1,
    "albania":0.3,
    "armenia":1.6,
    "austria":2.5,
    "azerbaijan":2.1,
    "belarus":2,
    "belgium":2.7,
    "bosnia & Herzegovina":0,
    "bulgaria":2,
    "croatia":1.3,
    "cyprus":1.7,
    "denmark":4.8,
    "estonia":8.3,
    "f.Y.R. Macedonia":0,
    "finland":1.3,
    "france":1.4,
    "georgia":2.8,
    "germany":2.7,
    "greece":0.7,
    "hungary":1.5,
    "iceland":1.8,
    "ireland":2.1,
    "israel":0.6,
    "italy":3,
    "lithuania":6.1,
    "malta":2.5,
    "moldova":1,
    "montenegro":0,
    "norway":4.7,
    "poland":1.6,
    "portugal":1.2,
    "romania":0.4,
    "russia":7.9,
    "san marino":0,
    "serbia":1.3,
    "slovenia":1.2,
    "spain":0.9,
    "sweden":3.9,
    "switzerland":2.5,
    "the Netherlands":2,
    "turkey":0.2,
    "u.K.":1.6,
    "ukraine":5.9
},

"lithuania": {
    "lithuania":-1,
    "slovakia":-1,
    "albania":0,
    "armenia":0.3,
    "austria":2,
    "azerbaijan":6.3,
    "belarus":2.8,
    "belgium":1.8,
    "bosnia & Herzegovina":0.3,
    "bulgaria":0,
    "croatia":1.5,
    "cyprus":1.7,
    "denmark":1.8,
    "estonia":6.9,
    "f.Y.R. Macedonia":0,
    "finland":2,
    "france":2.2,
    "georgia":9.8,
    "germany":1.1,
    "greece":1.5,
    "hungary":1.5,
    "iceland":1.6,
    "ireland":2,
    "israel":0.8,
    "italy":3.5,
    "latvia":10,
    "malta":1.8,
    "moldova":2,
    "montenegro":0,
    "norway":3.2,
    "poland":2.8,
    "portugal":0,
    "romania":0.3,
    "russia":7.5,
    "san marino":0,
    "serbia":1.7,
    "slovenia":2.5,
    "spain":0.9,
    "sweden":3.4,
    "switzerland":2,
    "the Netherlands":4,
    "turkey":0.7,
    "u.K.":1.6,
    "ukraine":5.5
},

"malta": {
    "malta":-1,
    "albania":1.8,
    "armenia":1,
    "austria":2.6,
    "azerbaijan":7,
    "belarus":3,
    "belgium":1.3,
    "bosnia & Herzegovina":0.4,
    "bulgaria":7,
    "croatia":3.7,
    "cyprus":4,
    "denmark":3.4,
    "estonia":2.3,
    "f.Y.R. Macedonia":0.8,
    "finland":0.9,
    "france":0.2,
    "georgia":1,
    "germany":1.3,
    "greece":3.9,
    "hungary":0.3,
    "iceland":3.1,
    "ireland":2.5,
    "israel":2.6,
    "italy":8,
    "latvia":3.5,
    "lithuania":0.7,
    "moldova":0.3,
    "montenegro":0,
    "norway":2.6,
    "poland":1,
    "portugal":0.3,
    "romania":2.9,
    "russia":2.9,
    "san marino":0,
    "serbia":2.9,
    "slovakia":4,
    "slovenia":1.4,
    "spain":1.5,
    "sweden":4.5,
    "switzerland":1.8,
    "the Netherlands":2.7,
    "turkey":2.8,
    "u.K.":4.6,
    "ukraine":3.8
},

"moldova": {
    "moldova":-1,
    "slovakia":-1,
    "albania":0,
    "armenia":3,
    "austria":3.5,
    "azerbaijan":7.6,
    "belarus":5.5,
    "belgium":0,
    "bosnia & Herzegovina":0.6,
    "bulgaria":3,
    "croatia":0.5,
    "cyprus":0,
    "denmark":1.2,
    "estonia":3.8,
    "f.Y.R. Macedonia":0,
    "finland":0.9,
    "france":0.2,
    "georgia":4.4,
    "germany":0.2,
    "greece":2.2,
    "hungary":0.8,
    "iceland":0.4,
    "ireland":0,
    "israel":2.6,
    "italy":1.3,
    "latvia":3,
    "lithuania":0.7,
    "malta":0,
    "montenegro":0,
    "norway":2.6,
    "poland":1,
    "portugal":0,
    "romania":11.3,
    "russia":8,
    "san marino":1,
    "serbia":1.7,
    "slovenia":0,
    "spain":0.4,
    "sweden":3.1,
    "switzerland":0,
    "the Netherlands":0,
    "turkey":0.1,
    "u.K.":0.5,
    "ukraine":8
},

"monaco": {
    "azerbaijan":-1,
    "belarus":-1,
    "bulgaria":-1,
    "estonia":-1,
    "georgia":-1,
    "italy":-1,
    "montenegro":-1,
    "portugal":-1,
    "san marino":-1,
    "slovakia":-1,
    "slovenia":-1,
    "albania":0,
    "armenia":0,
    "austria":0,
    "belgium":0,
    "bosnia & Herzegovina":5.3,
    "croatia":3.7,
    "cyprus":1,
    "denmark":5,
    "f.Y.R. Macedonia":0.3,
    "finland":0,
    "france":5,
    "germany":3,
    "greece":3.3,
    "hungary":0,
    "iceland":5,
    "ireland":5,
    "israel":6,
    "latvia":4,
    "lithuania":7,
    "malta":1.7,
    "moldova":0,
    "norway":0.3,
    "poland":0,
    "romania":1.3,
    "russia":0,
    "serbia":3.5,
    "spain":1,
    "sweden":2.7,
    "switzerland":7,
    "the Netherlands":0,
    "turkey":2.7,
    "u.K.":0,
    "ukraine":2.7
},

"montenegro": {
    "montenegro":-1,
    "slovakia":-1,
    "albania":8,
    "armenia":2.2,
    "austria":2,
    "azerbaijan":4.6,
    "belarus":2.3,
    "belgium":0,
    "bosnia & Herzegovina":8.8,
    "bulgaria":5,
    "croatia":5,
    "cyprus":0,
    "denmark":2,
    "estonia":0,
    "f.Y.R. Macedonia":9,
    "finland":0,
    "france":0.2,
    "georgia":0.7,
    "germany":0,
    "greece":2.7,
    "hungary":3,
    "iceland":1,
    "ireland":0,
    "israel":4.5,
    "italy":4.7,
    "latvia":1.5,
    "lithuania":0.3,
    "malta":0,
    "moldova":2,
    "norway":2.8,
    "poland":2,
    "portugal":0,
    "romania":0.2,
    "russia":4.2,
    "san marino":0,
    "serbia":12,
    "slovenia":8,
    "spain":0.7,
    "sweden":1.7,
    "switzerland":5,
    "the Netherlands":0,
    "turkey":1,
    "u.K.":0,
    "ukraine":2.2
},

"norway": {
    "norway":-1,
    "albania":0.5,
    "armenia":0,
    "austria":3,
    "azerbaijan":2.4,
    "belarus":0,
    "belgium":1.8,
    "bosnia & Herzegovina":3.7,
    "bulgaria":0,
    "croatia":1.8,
    "cyprus":1,
    "denmark":7.1,
    "estonia":2.6,
    "f.Y.R. Macedonia":0,
    "finland":4.2,
    "france":2,
    "georgia":0.2,
    "germany":2,
    "greece":1.2,
    "hungary":1.3,
    "iceland":6.4,
    "ireland":2.7,
    "israel":1.8,
    "italy":0.8,
    "latvia":3.8,
    "lithuania":2,
    "malta":3.2,
    "moldova":0.5,
    "montenegro":0,
    "poland":1.6,
    "portugal":1.3,
    "romania":2.2,
    "russia":2.8,
    "san marino":0,
    "serbia":5.4,
    "slovakia":0,
    "slovenia":0,
    "spain":0.3,
    "sweden":8.5,
    "switzerland":0.4,
    "the Netherlands":3.7,
    "turkey":2.7,
    "u.K.":1.1,
    "ukraine":1.3
},

"poland": {
    "poland":-1,
    "albania":0.4,
    "armenia":5.8,
    "austria":1.8,
    "azerbaijan":5.8,
    "belarus":2.3,
    "belgium":5.1,
    "bosnia & Herzegovina":0.6,
    "bulgaria":0,
    "croatia":1.7,
    "cyprus":1.6,
    "denmark":4,
    "estonia":5.6,
    "f.Y.R. Macedonia":0,
    "finland":2.8,
    "france":2.1,
    "georgia":4,
    "germany":3.1,
    "greece":1.8,
    "hungary":2.4,
    "iceland":0.8,
    "ireland":2,
    "israel":2.5,
    "italy":6,
    "latvia":0.8,
    "lithuania":3.3,
    "malta":1.7,
    "moldova":2.3,
    "montenegro":0,
    "norway":4.4,
    "portugal":0,
    "romania":2.2,
    "russia":2,
    "san marino":0,
    "serbia":3.8,
    "slovakia":2.5,
    "slovenia":1.6,
    "spain":1,
    "sweden":2.9,
    "switzerland":2.3,
    "the Netherlands":3,
    "turkey":0.7,
    "u.K.":1.9,
    "ukraine":8.2
},

"portugal": {
    "portugal":-1,
    "albania":0,
    "armenia":1.3,
    "austria":4.3,
    "azerbaijan":1.3,
    "belarus":0.3,
    "belgium":2.7,
    "bosnia & Herzegovina":0.1,
    "bulgaria":6,
    "croatia":2.1,
    "cyprus":1.3,
    "denmark":2.7,
    "estonia":1.7,
    "f.Y.R. Macedonia":0,
    "finland":0.8,
    "france":1.9,
    "georgia":0.3,
    "germany":3.3,
    "greece":1.5,
    "hungary":1.3,
    "iceland":2.2,
    "ireland":2.9,
    "israel":2.5,
    "italy":6,
    "latvia":2.3,
    "lithuania":0.6,
    "malta":0.6,
    "moldova":7.4,
    "montenegro":0,
    "norway":2.5,
    "poland":0.3,
    "romania":4.5,
    "russia":2.4,
    "san marino":0,
    "serbia":2.4,
    "slovakia":0,
    "slovenia":1.3,
    "spain":6.8,
    "sweden":3.4,
    "switzerland":1.7,
    "the Netherlands":4,
    "turkey":1.1,
    "u.K.":2.9,
    "ukraine":6.1
},

"romania": {
    "romania":-1,
    "albania":0.5,
    "armenia":3.6,
    "austria":1.3,
    "azerbaijan":3.7,
    "belarus":0.3,
    "belgium":1.7,
    "bosnia & Herzegovina":0.6,
    "bulgaria":5,
    "croatia":1.6,
    "cyprus":2.3,
    "denmark":2.6,
    "estonia":1.1,
    "f.Y.R. Macedonia":3.1,
    "finland":0.8,
    "france":0.7,
    "georgia":0,
    "germany":1.1,
    "greece":7.1,
    "hungary":5.9,
    "iceland":1,
    "ireland":1.2,
    "israel":2.8,
    "italy":1.8,
    "latvia":0.3,
    "lithuania":0.1,
    "malta":1.5,
    "moldova":11.8,
    "montenegro":0,
    "norway":1.8,
    "poland":2.8,
    "portugal":0,
    "russia":3.9,
    "san marino":0,
    "serbia":4.6,
    "slovakia":0,
    "slovenia":1.5,
    "spain":2.2,
    "sweden":3.5,
    "switzerland":1.3,
    "the Netherlands":0.8,
    "turkey":5.8,
    "u.K.":1.3,
    "ukraine":2.3
},

"russia": {
    "russia":-1,
    "slovakia":-1,
    "albania":0,
    "armenia":8.7,
    "austria":1.1,
    "azerbaijan":9.9,
    "belarus":6.5,
    "belgium":3.3,
    "bosnia & Herzegovina":0.4,
    "bulgaria":4,
    "croatia":1.5,
    "cyprus":2.1,
    "denmark":1.9,
    "estonia":2.8,
    "f.Y.R. Macedonia":1,
    "finland":0.9,
    "france":2.2,
    "georgia":7,
    "germany":1.6,
    "greece":3.7,
    "hungary":1.4,
    "iceland":0.7,
    "ireland":0.8,
    "israel":2.7,
    "italy":1.4,
    "latvia":2.1,
    "lithuania":3.3,
    "malta":2.5,
    "moldova":5,
    "montenegro":0,
    "norway":3.4,
    "poland":0,
    "portugal":0,
    "romania":2.8,
    "san marino":0,
    "serbia":4.1,
    "slovenia":3.6,
    "spain":1.2,
    "sweden":1.8,
    "switzerland":1.7,
    "the Netherlands":2.4,
    "turkey":1.1,
    "u.K.":1.6,
    "ukraine":6.9
},

"san marino": {
    "bulgaria":-1,
    "san marino":-1,
    "slovakia":-1,
    "albania":7.5,
    "armenia":5,
    "austria":0,
    "azerbaijan":5.6,
    "belarus":0,
    "belgium":5,
    "bosnia & Herzegovina":0,
    "croatia":0,
    "cyprus":0,
    "denmark":1.4,
    "estonia":0,
    "f.Y.R. Macedonia":0,
    "finland":1.5,
    "france":2.2,
    "georgia":2.3,
    "germany":0,
    "greece":6.4,
    "hungary":3.3,
    "iceland":1.6,
    "ireland":0,
    "israel":10,
    "italy":5.8,
    "latvia":0,
    "lithuania":0,
    "malta":5.3,
    "moldova":2.7,
    "montenegro":0,
    "norway":3.5,
    "poland":0,
    "portugal":5,
    "romania":0.2,
    "russia":2,
    "serbia":3.7,
    "slovenia":0.5,
    "spain":0.2,
    "sweden":3.8,
    "switzerland":0,
    "the Netherlands":1,
    "turkey":4.5,
    "u.K.":2.6,
    "ukraine":0
},

"serbia": {
    "montenegro":-1,
    "san marino":-1,
    "serbia":-1,
    "slovakia":-1,
    "albania":1.8,
    "armenia":1,
    "austria":0,
    "azerbaijan":2,
    "belarus":0.7,
    "belgium":4,
    "bosnia & Herzegovina":9.6,
    "bulgaria":6,
    "croatia":7,
    "cyprus":3,
    "denmark":1.6,
    "estonia":0,
    "f.Y.R. Macedonia":9.3,
    "finland":1.2,
    "france":0.8,
    "georgia":0,
    "germany":0.9,
    "greece":5.9,
    "hungary":6,
    "iceland":0,
    "ireland":0,
    "israel":1.4,
    "italy":2,
    "latvia":0,
    "lithuania":1.7,
    "malta":2.6,
    "moldova":1.5,
    "norway":3.3,
    "poland":0,
    "portugal":1,
    "romania":1.7,
    "russia":4.6,
    "slovenia":7.5,
    "spain":0,
    "sweden":1.9,
    "switzerland":1.7,
    "the Netherlands":0,
    "turkey":0.4,
    "u.K.":0.9,
    "ukraine":3.8
},

"slovakia": {
    "bulgaria":-1,
    "latvia":-1,
    "montenegro":-1,
    "san marino":-1,
    "slovakia":-1,
    "albania":0,
    "armenia":3.5,
    "austria":3,
    "azerbaijan":4.3,
    "belarus":0,
    "belgium":5.7,
    "bosnia & Herzegovina":2,
    "croatia":5,
    "cyprus":4.3,
    "denmark":3.3,
    "estonia":6,
    "f.Y.R. Macedonia":2,
    "finland":0,
    "france":0,
    "georgia":0,
    "germany":2.4,
    "greece":2.2,
    "hungary":2.7,
    "iceland":2.2,
    "ireland":3.8,
    "israel":4.3,
    "italy":2.5,
    "lithuania":0,
    "malta":6,
    "moldova":1.3,
    "norway":2.6,
    "poland":1,
    "portugal":1,
    "romania":0.2,
    "russia":2.3,
    "serbia":2.3,
    "slovenia":0.3,
    "spain":0.3,
    "sweden":5.2,
    "switzerland":1.3,
    "the Netherlands":3,
    "turkey":0,
    "u.K.":2.3,
    "ukraine":3.3
},

"slovenia": {
    "slovenia":-1,
    "albania":2.2,
    "armenia":0.7,
    "austria":3.2,
    "azerbaijan":0.7,
    "belarus":0,
    "belgium":1.2,
    "bosnia & Herzegovina":6.3,
    "bulgaria":7,
    "croatia":8.1,
    "cyprus":1.2,
    "denmark":4.8,
    "estonia":3.5,
    "f.Y.R. Macedonia":5.4,
    "finland":0.8,
    "france":1.5,
    "georgia":0.6,
    "germany":2.1,
    "greece":1.6,
    "hungary":0.6,
    "iceland":1.6,
    "ireland":1.6,
    "israel":2.5,
    "italy":5.2,
    "latvia":2.6,
    "lithuania":0.6,
    "malta":1.2,
    "moldova":0.6,
    "montenegro":7,
    "norway":3.6,
    "poland":1.1,
    "portugal":0,
    "romania":0.9,
    "russia":3.5,
    "san marino":0,
    "serbia":10.9,
    "slovakia":0,
    "spain":0.9,
    "sweden":3.9,
    "switzerland":1.5,
    "the Netherlands":3.2,
    "turkey":0.9,
    "u.K.":1.5,
    "ukraine":1.8
},

"spain": {
    "spain":-1,
    "albania":0,
    "armenia":6,
    "austria":3.4,
    "azerbaijan":2,
    "belarus":0,
    "belgium":3.9,
    "bosnia & Herzegovina":0.3,
    "bulgaria":10,
    "croatia":2.3,
    "cyprus":3,
    "denmark":3.1,
    "estonia":2.1,
    "f.Y.R. Macedonia":0,
    "finland":0.9,
    "france":1.5,
    "georgia":0.2,
    "germany":4.7,
    "greece":2.9,
    "hungary":1.6,
    "iceland":1.6,
    "ireland":1.3,
    "israel":2.1,
    "italy":6.6,
    "latvia":2.6,
    "lithuania":0.6,
    "malta":3.1,
    "moldova":3.3,
    "montenegro":0,
    "norway":2.2,
    "poland":0.8,
    "portugal":3.6,
    "romania":7.7,
    "russia":2.4,
    "san marino":0,
    "serbia":1.6,
    "slovakia":1,
    "slovenia":1.4,
    "sweden":3.4,
    "switzerland":0.3,
    "the Netherlands":2.4,
    "turkey":2.1,
    "u.K.":1.6,
    "ukraine":4.2
},

"sweden": {
    "sweden":-1,
    "albania":1.5,
    "armenia":1.6,
    "austria":3.3,
    "azerbaijan":1.6,
    "belarus":0,
    "belgium":1.4,
    "bosnia & Herzegovina":4.6,
    "bulgaria":0,
    "croatia":0.7,
    "cyprus":2.7,
    "denmark":7.2,
    "estonia":5.7,
    "f.Y.R. Macedonia":0,
    "finland":6.4,
    "france":1.3,
    "georgia":1.2,
    "germany":1.6,
    "greece":2.3,
    "hungary":2.6,
    "iceland":4.7,
    "ireland":3.7,
    "israel":0.9,
    "italy":0.6,
    "latvia":2.6,
    "lithuania":0.4,
    "malta":1.8,
    "moldova":0.3,
    "montenegro":0,
    "norway":6.2,
    "poland":0.8,
    "portugal":0.4,
    "romania":1.5,
    "russia":1.8,
    "san marino":0,
    "serbia":7,
    "slovakia":0,
    "slovenia":1.3,
    "spain":1,
    "switzerland":0.6,
    "the Netherlands":4.3,
    "turkey":2.6,
    "u.K.":1.8,
    "ukraine":1.3
},

"switzerland": {
    "switzerland":-1,
    "albania":8.5,
    "armenia":0,
    "austria":4.3,
    "azerbaijan":1.3,
    "belarus":0,
    "belgium":1.6,
    "bosnia & Herzegovina":4.7,
    "bulgaria":0,
    "croatia":3.7,
    "cyprus":1.2,
    "denmark":1.4,
    "estonia":0,
    "f.Y.R. Macedonia":1.6,
    "finland":1.6,
    "france":1.6,
    "georgia":0.2,
    "germany":6,
    "greece":2.6,
    "hungary":1.8,
    "iceland":1.8,
    "ireland":3.5,
    "israel":1.8,
    "italy":6.6,
    "latvia":2.5,
    "lithuania":0,
    "malta":1.3,
    "moldova":0.3,
    "montenegro":0,
    "norway":2.2,
    "poland":0,
    "portugal":5.8,
    "romania":0.4,
    "russia":0.1,
    "san marino":0,
    "serbia":10.6,
    "slovakia":0,
    "slovenia":0.3,
    "spain":4.3,
    "sweden":1.7,
    "the Netherlands":3.4,
    "turkey":5.8,
    "u.K.":1.7,
    "ukraine":0.2
},

"the Netherlands": {
    "the Netherlands":-1,
    "albania":0.2,
    "armenia":8,
    "austria":3.7,
    "azerbaijan":2.9,
    "belarus":0,
    "belgium":7.9,
    "bosnia & Herzegovina":3.2,
    "bulgaria":0,
    "croatia":1.1,
    "cyprus":2,
    "denmark":3.6,
    "estonia":2.9,
    "f.Y.R. Macedonia":0,
    "finland":1,
    "france":1.1,
    "georgia":0.4,
    "germany":3.4,
    "greece":2.8,
    "hungary":1.9,
    "iceland":2,
    "ireland":2.3,
    "israel":3.3,
    "italy":1.4,
    "latvia":0.5,
    "lithuania":1.5,
    "malta":2,
    "moldova":0,
    "montenegro":0,
    "norway":3.7,
    "poland":0.6,
    "portugal":1.2,
    "romania":0.9,
    "russia":1.4,
    "san marino":0,
    "serbia":6.3,
    "slovakia":0,
    "slovenia":1.3,
    "spain":1.6,
    "sweden":3.6,
    "switzerland":1,
    "turkey":7.6,
    "u.K.":1.4,
    "ukraine":1.8
},

"turkey": {
    "montenegro":-1,
    "san marino":-1,
    "turkey":-1,
    "albania":5.2,
    "armenia":8.8,
    "austria":3.4,
    "azerbaijan":12,
    "belarus":0,
    "belgium":2,
    "bosnia & Herzegovina":7.3,
    "bulgaria":6,
    "croatia":3.6,
    "cyprus":0.1,
    "denmark":0.9,
    "estonia":2,
    "f.Y.R. Macedonia":3,
    "finland":0.8,
    "france":0.4,
    "georgia":5.5,
    "germany":2.2,
    "greece":3.3,
    "hungary":1.4,
    "iceland":1.5,
    "ireland":3.1,
    "israel":1.5,
    "italy":1.7,
    "latvia":0.8,
    "lithuania":0,
    "malta":4.6,
    "moldova":3.1,
    "norway":1.9,
    "poland":0.8,
    "portugal":1.1,
    "romania":2.5,
    "russia":2.9,
    "serbia":1.1,
    "slovakia":0,
    "slovenia":1.5,
    "spain":1.4,
    "sweden":2.7,
    "switzerland":0,
    "the Netherlands":2.1,
    "u.K.":2.3,
    "ukraine":3.9
},

"u.K.": {
    "u.K.":-1,
    "albania":0.3,
    "armenia":0,
    "austria":3.5,
    "azerbaijan":0.7,
    "belarus":0,
    "belgium":2.4,
    "bosnia & Herzegovina":0.3,
    "bulgaria":5,
    "croatia":0.5,
    "cyprus":3.4,
    "denmark":4.4,
    "estonia":4.4,
    "f.Y.R. Macedonia":0,
    "finland":1.6,
    "france":1.2,
    "georgia":0,
    "germany":2.4,
    "greece":5.2,
    "hungary":1.1,
    "iceland":2.7,
    "ireland":6.4,
    "israel":2.7,
    "italy":2,
    "latvia":4.6,
    "lithuania":3.8,
    "malta":5,
    "moldova":1.3,
    "montenegro":0,
    "norway":2.8,
    "poland":0.6,
    "portugal":0.2,
    "romania":1.2,
    "russia":1.6,
    "san marino":0,
    "serbia":0.4,
    "slovakia":0,
    "slovenia":1.5,
    "spain":1.4,
    "sweden":4.8,
    "switzerland":1.6,
    "the Netherlands":3.3,
    "turkey":4.2,
    "ukraine":2.5
},

"ukraine": {
    "slovakia":-1,
    "ukraine":-1,
    "albania":0,
    "armenia":6.3,
    "austria":2,
    "azerbaijan":9.3,
    "belarus":7.5,
    "belgium":2.8,
    "bosnia & Herzegovina":1,
    "bulgaria":3,
    "croatia":2.7,
    "cyprus":0.8,
    "denmark":1.1,
    "estonia":1.4,
    "f.Y.R. Macedonia":1.2,
    "finland":1,
    "france":0.7,
    "georgia":8.4,
    "germany":0.8,
    "greece":1.8,
    "hungary":1.5,
    "iceland":0.4,
    "ireland":0.4,
    "israel":2.7,
    "italy":1,
    "latvia":1,
    "lithuania":1,
    "malta":2.5,
    "moldova":6.1,
    "montenegro":0,
    "norway":3.7,
    "poland":5,
    "portugal":1.5,
    "romania":0.9,
    "russia":8.7,
    "san marino":0,
    "serbia":3.3,
    "slovenia":1,
    "spain":0.5,
    "sweden":2.9,
    "switzerland":1.3,
    "the Netherlands":0,
    "turkey":2.3,
    "u.K.":0.8
}
}

var list = Object.keys(countries);


function createOptions(sel) {
	$(list).each(function() {
	 sel.append($("<option>").text(this));
	});
}

var selTop = $('<select>').appendTo("div#countriesAbove");
createOptions(selTop);
selTop.val("sweden");

var selBottom = $('<select>').appendTo("div#countriesBelow");
createOptions(selBottom);
selBottom.val("france");

selTop.change(function() {
  $("#flagAbove").attr('src', "images/" + $(this).val() + ".svg");
  // var that = this;
  // $("#flagAbove").css({opacity: 0});
  // setTimeout(function() {
  //   $("#flagAbove").attr('src', "images/" + $(that).val() + ".svg");
  //   $("#flagAbove").css({opacity: 1});
  // }, 500);
  checkValues();
});

selBottom.change(function() {
  var that = this;
  $("#flagBelow").css({opacity: 0});
  setTimeout(function() {
    $("#flagBelow").attr('src', "images/" + $(that).val() + ".svg");
    $("#flagBelow").css({opacity: 1});
  }, 500);
  checkValues();
});

function capitaliseFirstLetter(string)
{
    return string.charAt(0).toUpperCase() + string.slice(1);
}


function checkValues () {

  var country1 = selTop.val();
  var country2 = selBottom.val();
  // $("#result").text(countries[country1][country2] + ':' + countries[country2][country1]);


    // var country1Number = countries[country1][country2];
    // var country2Number = countries[country2][country1];



    var country1Number = (countries[country1][country2] === undefined) ? -1 : countries[country1][country2]
    var country2Number = (countries[country2][country1] === undefined) ? -1 : countries[country2][country1]
    var countriesAverage = (country1Number + country2Number)/2; 
    countriesAverage = countriesAverage.toFixed(2);
    

              // $("#heartsAbove").css({opacity: 0});
              // setTimeout(function() {
              //   $("#heartsAbove").attr('src', "images/hearts.svg");
              //   $("#heartsAbove").css({opacity: 1});
              // }, 500);
              // checkValues();
         
              // var that = this;
              // $("#heartsBelow").css({opacity: 0});
              // setTimeout(function() {
              //   $("#heartsBelow").attr('src', "images/hearts.svg");
              //   $("#heartsBelow").css({opacity: 1});
              // }, 500);
              // checkValues();

 //if statement for undefined

    if (country1 === country2) {
      $("#result").text("As Whitney told us, loving yourself is greatest love of all, but we're pretty sure " + capitaliseFirstLetter(selTop.val()) + " can't vote for itself.");
      $("#heartsAbove").attr('src', "images/hearts.svg");
      $("#heartsBelow").attr('src', "images/hearts.svg");
    } 
// if the XY country averages are the same then display a reltionship status of IN LOVE

    else if (country1Number === country2Number) {
    	$("#result").text(capitaliseFirstLetter(selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " have been going steady and know that giving is as important as receiving. They awarded each other " + country1Number + " points.");
        $("#heartsAbove").attr('src', "images/hearts.svg");
        $("#heartsBelow").attr('src', "images/hearts.svg");
    } 

// if the difference is <2 display a reltionship status of IN LOVE

    else if (country1Number-country2Number <=1.5 && country1Number-country2Number >=0 && countriesAverage >=6) {
        $("#result").text(capitaliseFirstLetter(selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " have been going steady and know that giving is as important as receiving. They awarded each other an average of " + countriesAverage + " points.");
        $("#heartsAbove").attr('src', "images/hearts.svg");
        $("#heartsBelow").attr('src', "images/hearts.svg");
    }

    else if (country2Number-country1Number <=1.5 && country2Number-country1Number >=0 && countriesAverage >=6) {
        $("#result").text(capitaliseFirstLetter(selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " have been going steady and know that giving is as important as receiving. They awarded each other an average of " + countriesAverage + " points.");
        $("#heartsAbove").attr('src', "images/hearts.svg");
        $("#heartsBelow").attr('src', "images/hearts.svg");
    }

     else if (country1Number-country2Number <=1.5 && country1Number-country2Number >=0 && countriesAverage <6 && countriesAverage >=0) {
        $("#result").text(capitaliseFirstLetter(selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " have been going steady, but they are saving all their love for someone else and only awarding each other an average of " + countriesAverage + " points.");
        $("#heartsAbove").attr('src', "images/hearts.svg");
        $("#heartsBelow").attr('src', "images/hearts.svg");
    }

    else if (country2Number-country1Number <=1.5 && country2Number-country1Number >=0 && countriesAverage <6 && countriesAverage >=0) {
        $("#result").text(capitaliseFirstLetter(selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " have been going steady, but they are saving all their love for someone else and only awarding each other an average of " + countriesAverage + " points.");
        $("#heartsAbove").attr('src', "images/hearts.svg");
        $("#heartsBelow").attr('src', "images/hearts.svg");
    }  
    
// end of love 

    else if (country1Number<=0 && country2Number<=0) {
        $("#result").text("Yeah, " + (selTop.val()) + " and " + capitaliseFirstLetter(selBottom.val()) + " aren't in a good place. They basically haven't spoken in 20 years and certainly haven't awarded each other any eurovison points.");
        $("#heartsAbove").attr('src',"images/broken.svg");
        $("#heartsBelow").attr('src', "images/broken.svg");
    } 

    else if (country1Number > country2Number && country2Number >=0) {
    	$("#result").text("Bit stormy with these two. " + capitaliseFirstLetter(selTop.val()) + " is giving all the love with an average of " + country1Number + " points, but " + capitaliseFirstLetter(selBottom.val()) + " has been casting serious sideye with only " + country2Number + " points.");
        $("#heartsAbove").attr('src',"images/hearts.svg");
        $("#heartsBelow").attr('src',"images/broken.svg");
    } 

    else if (country1Number < country2Number && country1Number >=0) {
    	$("#result").text("Bit stormy with these two. " + capitaliseFirstLetter(selBottom.val()) + " is giving all the love with an average of " + country2Number + " points, but " + capitaliseFirstLetter(selTop.val()) + " has been casting serious sideye with only " + country1Number + " points.");
        $("#heartsAbove").attr('src',"images/broken.svg");
        $("#heartsBelow").attr('src',"images/hearts.svg");
    }

    else if (country1Number === -1 && country2Number >=0) {
        $("#result").text("Serious missed connection here." + capitaliseFirstLetter(selTop.val()) + " hasn't been around to show the love. Despite this " + capitaliseFirstLetter(selBottom.val()) + " has awarded " + country2Number + " points.");
        $("#heartsAbove").attr('src',"images/broken.svg");
        $("#heartsBelow").attr('src',"images/broken.svg");
    }
       
    else if (country2Number === -1 && country1Number >=0) {
        $("#result").text("Serious missed connection here." + capitaliseFirstLetter(selBottom.val()) + " hasn't been around to show the love. Despite this " + capitaliseFirstLetter(selTop.val()) + " has awarded " + country1Number + " points.");
        $("#heartsAbove").attr('src',"images/broken.svg");
        $("#heartsBelow").attr('src',"images/broken.svg");
    }

    else if (country1Number === -1 && country2Number === -1) {
        $("#result").text("Like ships passing in the night, these two haven't been in a final together and, alas, haven't had a chance to show their Eurovision love.");
        $("#heartsAbove").attr('src',"images/broken.svg");
        $("#heartsBelow").attr('src',"images/broken.svg");
    }



}





// LOGIC
// if same country is selected for both entries
// if country1 and country2 are equal
// if country1 awarded the same amount of points as country2
// if country1 and country2 didnt award ANY points 
//     should I put in the negative condition here?

// if the difference between country1 and country2 is less than two or three
//     and the individual scores are over 6

// if the difference between country1 and country2 is less than two or three
//     and the individual scores less than six







